# To execute a job locally, install gitlab-runner (https://docs.gitlab.com/runner/install/)
# and run the following command:
# gitlab-runner exec docker --docker-privileged --docker-volumes /sys/fs/cgroup:/sys/fs/cgroup:rw <<JOB_NAME>>

image: registry.gitlab.com/sosy-lab/benchmarking/competition-scripts/python:latest

# Do not checkout any submodules for now; sv-benchmarks and archives-20xx are just too big.
# Set depth to 10, such that new commits in one of the submodules makes do not break the CI immediately.
variables:
  GIT_SUBMODULE_STRATEGY: normal
  GIT_STRATEGY: fetch
  GIT_DEPTH: "10"

check-definitions:
  script:
    - ./scripts/test/check-benchdef-svcomp.py benchmark-defs/*xml


