# Do not checkout any submodules for now; sv-benchmarks and archives-20xx are just too big
variables:
    GIT_SUBMODULE_STRATEGY: none

image: ${CI_REGISTRY_IMAGE}/test

check-definitions:
  script:
    - ./test/check.py benchmark-defs/*xml

.build-docker:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --dockerfile $CI_PROJECT_DIR/$DOCKERFILE --destination $CI_REGISTRY_IMAGE/$IMAGE
  only:
    - schedules
    - web

build-docker:test:latest:
  extends: .build-docker
  stage: images
  variables:
    DOCKERFILE: test/Dockerfile.test
    IMAGE: test:latest
